### ISSUE TITLE
Wear Installer 2 crashing when installing apk, assuming it's related to the Android Version on the phone or a possible bug when creating APK in Watch Face Studio

### ISSUE THREAD

**Issue by sderaps** [sderaps/DMM#2]
One person is Reporting Wear Installer 2 is crashing,  I personally have not experienced any issues installing any apks including my own via wear installer 2, but am opening this issue to see if more people are having the same problem.  

I Created the apk in Samsung Watch Face Studio.

**Comment by sderaps** [comment]
for this user,  Sideloading the apk from windows to watch using ADB Commands solved this users problem and they were able to successfully install watch face . Apparently Wear installed 2 would crash on there phone.

**Comment by sderaps** [comment]
apparently this user was only able to install the apk via windows adb commands, and sending file to watch due to wear Installer 2 crashing on their phone.

**Comment by PhilTU** [comment]
I can't see apk to test

**Comment by sderaps** [comment]
It on the right hand side of the dmm page in "releases" But here is a direct link, Click Here scroll doown to the bottom of the page: https://github.com/sderaps/DMM/releases/tag/v1.0.1

**Comment by PhilTU** [comment]
Thanks. Releases is hiding on my phone Web view.

I too have the Wear Installer 2 issue, as I select your apk it closes and reopens back at the selection screen.

**Comment by PhilTU** [comment]
As a further check I downloaded freepoc Where I am 2 WearOS apk and it did not crash WI2 when selected

**Comment by sderaps** [comment]
Looks like sideloading via ADB on a computer is the only method for you too. Sorry , I will get to the bottom of this.. I'm going to take an old phone, remove my account and try to reproduce to problem.. This is very helpful information  Thanks

**Comment by sderaps** [comment]
Wear installer 2 Help Page here: https://freepoc.org/wear-installer-2-help-page/

**Comment by sderaps** [comment]
> As a further check I downloaded freepoc Where I am 2 WearOS apk and it did not crash WI2 when selected

Ok I understand now, so You got it working then?

**Comment by sderaps** [comment]
user reported: """I could not install your apk on the watch with WI2
I could install another apk from the WI2 developer without the same problem
The problem was WI2 closed when I selected your apk""

**Comment by sderaps** [comment]
Problem solved, watch face apks require a phone version of android 11 or higher to install with wear installer 2, other wise APK must be sideloaded using ADB on Computer..  Watch Requires Wear os 3 or higher. I will have to update (min requirements) on main page

**Comment by sderaps** [comment]
Problem solved, watch face apks require a phone version of android 11 or higher to install with wear installer 2, other wise APK must be sideloaded using ADB on Computer.. Watch Requires Wear os 3 or higher. I will have to update (min requirements) on main page
